# Lecture 3
AI Intro, 22.2.2024

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Python 基础
python属于弱类型语言，不需要声明变量的类型

In [2]:
a = 10

In [3]:
b = [3, 1, 4, 1, 5, 9]
b[2] = True
b[3] = "a"
b

[3, 1, True, 'a', 5, 9]

In [4]:
b:int = 10
b

10

python中无换行符，用缩进

In [9]:
def myfunc():
    a = 1
    b = 2
    return 1

In [10]:
def func(){
    return 1
}

SyntaxError: expected ':' (3433137271.py, line 1)

### Python的数字类型及运算符

In [11]:
type(1)

int

In [12]:
type(1.0)

float

In [13]:
type(True)

bool

以上三种数据类型在底层都是用class来实现的

#### 查看某种数据是什么类型

In [14]:
isinstance(1, int)

True

In [15]:
type(1) == int

True

Python的所有运算类型都符合直觉。

### Python的变量命名

In [16]:
1a = 1

SyntaxError: invalid decimal literal (1364191551.py, line 1)

In [17]:
_a = 1

In [18]:
_a

1

注：命名要符合规范、区分大小写

In [19]:
a = (2, 3)
type(a)

tuple

In [20]:
a[0] = 1

TypeError: 'tuple' object does not support item assignment

In [21]:
a = 2
b = 4
c = [a, b]
c[0] = 5
a

2

In [22]:
d = a
d = 5
a

2

In [23]:
e = c
e[0] = 5
c

[5, 4]

In [24]:
# another test
c = [2, 3]
e = c
e[0] = 5
c

[5, 3]

### 判断和循环

In [25]:
score = 100
if score == 100:
    print("julao!!")
for i in [1, 2, 3, 4, 5]:
    print(i)

julao!!
1
2
3
4
5


### 函数和缩进

In [26]:
def myfunc(a):
    return a
myfunc(1)

1

## Numpy库

In [28]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [29]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
np.random.randn(3, 4)

array([[-0.18566243,  0.78850658, -0.36132369, -0.44398549],
       [-0.77109007, -0.73578198,  1.08820759,  1.32196329],
       [ 0.25629642, -0.08652767, -0.52636954, -1.66422676]])

## 搜索 Search

### 搜索的特性 the elements of search problem
* 目标 goal
* 状态 state (start state, goal state, current state)
* 动作 actions
* 状态转移方程 transition function
* 成本/代价方程 cost function

### 搜索问题的答案
一个序列的动作 a set of actions

### 搜索问题的解决方法：
构建列表

如果列表为空则失败

如果列表包含目标状态则成功

从列表移除节点

把某些和当前节点相关的节点加入列表

### 深度优先搜索 Depth First Search
“不撞南墙不死心”

先进先出-Stack

### 广度优先搜索 Bread First Search
“两边都探一步”

后进先出-Queue